# Generated by Django 5.2 on 2025-04-05 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expire_date', models.DateField()),
                ('status', models.CharField(choices=[('warehouse', 'On warehouse'), ('showcase', 'On showcase'), ('sold', 'Sold'), ('deleted', 'Deleted')], default='warehouse', max_length=20)),
                ('is_expired', models.BooleanField(default=False)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse_app.upload')),
            ],
        ),
    ]
