# Generated by Django 5.2 on 2025-04-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
